// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/google/uuid"
)

type AdminAuditEvent struct {
	ID         uuid.UUID `json:"id"`
	Action     string    `json:"action"`
	Actor      uuid.UUID `json:"actor"`
	Target     string    `json:"target"`
	Result     string    `json:"result"`
	OccurredAt time.Time `json:"occurredAt"`
}

type AdminConfigurationVersion struct {
	ID        uuid.UUID `json:"id"`
	Resource  string    `json:"resource"`
	Version   int       `json:"version"`
	Action    string    `json:"action"`
	Status    string    `json:"status"`
	Actor     uuid.UUID `json:"actor"`
	CreatedAt time.Time `json:"createdAt"`
}

type AdminEvaluationRubric struct {
	ID        uuid.UUID               `json:"id"`
	Name      string                  `json:"name"`
	Version   int                     `json:"version"`
	Criteria  []*AdminRubricCriterion `json:"criteria"`
	Status    AdminPromptStatus       `json:"status"`
	UpdatedAt time.Time               `json:"updatedAt"`
	UpdatedBy uuid.UUID               `json:"updatedBy"`
}

type AdminModel struct {
	ID            uuid.UUID         `json:"id"`
	ModelID       string            `json:"modelId"`
	DisplayName   string            `json:"displayName"`
	ProviderLabel string            `json:"providerLabel"`
	Roles         []AdminLLMRole    `json:"roles"`
	Status        AdminModelStatus  `json:"status"`
	LatencyClass  AdminLatencyClass `json:"latencyClass"`
	CreatedAt     time.Time         `json:"createdAt"`
	UpdatedAt     time.Time         `json:"updatedAt"`
}

type AdminPromptConfiguration struct {
	ID             uuid.UUID         `json:"id"`
	Role           AdminLLMRole      `json:"role"`
	Name           string            `json:"name"`
	Version        int               `json:"version"`
	PromptTemplate string            `json:"promptTemplate"`
	Status         AdminPromptStatus `json:"status"`
	UpdatedAt      time.Time         `json:"updatedAt"`
	UpdatedBy      uuid.UUID         `json:"updatedBy"`
}

type AdminRoutingRule struct {
	ID              uuid.UUID    `json:"id"`
	Role            AdminLLMRole `json:"role"`
	PrimaryModelID  string       `json:"primaryModelId"`
	FallbackModelID string       `json:"fallbackModelId"`
	TimeoutSeconds  int          `json:"timeoutSeconds"`
	Enabled         bool         `json:"enabled"`
	UpdatedAt       time.Time    `json:"updatedAt"`
	UpdatedBy       uuid.UUID    `json:"updatedBy"`
}

type AdminRubricCriterion struct {
	Name   string  `json:"name"`
	Weight float64 `json:"weight"`
}

type AdminRubricCriterionInput struct {
	Name   string  `json:"name"`
	Weight float64 `json:"weight"`
}

type AdminWorkspace struct {
	Models      []*AdminModel                `json:"models"`
	Prompts     []*AdminPromptConfiguration  `json:"prompts"`
	Rubric      *AdminEvaluationRubric       `json:"rubric,omitempty"`
	Routing     []*AdminRoutingRule          `json:"routing"`
	Versions    []*AdminConfigurationVersion `json:"versions"`
	AuditEvents []*AdminAuditEvent           `json:"auditEvents"`
}

type Answer struct {
	ID             uuid.UUID    `json:"id"`
	InterviewID    uuid.UUID    `json:"interviewId"`
	QuestionID     uuid.UUID    `json:"questionId"`
	Status         AnswerStatus `json:"status"`
	Text           *string      `json:"text,omitempty"`
	CodeLanguage   *string      `json:"codeLanguage,omitempty"`
	CodeContent    *string      `json:"codeContent,omitempty"`
	ContentHash    string       `json:"contentHash"`
	IdempotencyKey uuid.UUID    `json:"idempotencyKey"`
	SupersedesID   *uuid.UUID   `json:"supersedesId,omitempty"`
	SubmittedAt    time.Time    `json:"submittedAt"`
}

type CandidateInterviewAccess struct {
	AccessToken string     `json:"accessToken"`
	TokenClass  TokenClass `json:"tokenClass"`
	Interview   *Interview `json:"interview"`
}

type CreateAdminPromptVersionInput struct {
	Role           AdminLLMRole `json:"role"`
	Name           string       `json:"name"`
	PromptTemplate string       `json:"promptTemplate"`
}

type CreateInterviewInput struct {
	Title                string             `json:"title"`
	CandidateEmail       string             `json:"candidateEmail"`
	CandidateDisplayName string             `json:"candidateDisplayName"`
	PositionTitle        string             `json:"positionTitle"`
	Seniority            string             `json:"seniority"`
	TechnologyTags       []string           `json:"technologyTags"`
	Mode                 InterviewMode      `json:"mode"`
	Language             *InterviewLanguage `json:"language,omitempty"`
	QuestionSource       *QuestionSource    `json:"questionSource,omitempty"`
	RubricVersion        string             `json:"rubricVersion"`
	StartsAt             *time.Time         `json:"startsAt,omitempty"`
	ExpiresAt            time.Time          `json:"expiresAt"`
}

type CreateQuestionInput struct {
	InterviewID      uuid.UUID    `json:"interviewId"`
	Type             QuestionType `json:"type"`
	Prompt           string       `json:"prompt"`
	CompetencyIds    []string     `json:"competencyIds"`
	Difficulty       int          `json:"difficulty"`
	TimeLimitSeconds *int         `json:"timeLimitSeconds,omitempty"`
}

type CriterionScore struct {
	CriterionID        string   `json:"criterionId"`
	Applicable         bool     `json:"applicable"`
	Score              *float64 `json:"score,omitempty"`
	MaximumScore       float64  `json:"maximumScore"`
	Weight             float64  `json:"weight"`
	Confidence         float64  `json:"confidence"`
	EvidenceReferences []string `json:"evidenceReferences"`
	Rationale          string   `json:"rationale"`
	Limitations        []string `json:"limitations"`
}

type EvaluationReport struct {
	ID                            uuid.UUID         `json:"id"`
	InterviewID                   uuid.UUID         `json:"interviewId"`
	Status                        EvaluationStatus  `json:"status"`
	RubricID                      string            `json:"rubricId"`
	RubricVersion                 string            `json:"rubricVersion"`
	EvaluatorConfigurationVersion string            `json:"evaluatorConfigurationVersion"`
	OverallScore                  *float64          `json:"overallScore,omitempty"`
	OverallConfidence             float64           `json:"overallConfidence"`
	CriterionScores               []*CriterionScore `json:"criterionScores"`
	Strengths                     []string          `json:"strengths"`
	Gaps                          []string          `json:"gaps"`
	EvidenceReferences            []string          `json:"evidenceReferences"`
	Limitations                   []string          `json:"limitations"`
	HumanReview                   *HumanReview      `json:"humanReview"`
	GeneratedAt                   *time.Time        `json:"generatedAt,omitempty"`
	PublishedAt                   *time.Time        `json:"publishedAt,omitempty"`
	CreatedAt                     time.Time         `json:"createdAt"`
	UpdatedAt                     time.Time         `json:"updatedAt"`
}

type HumanReview struct {
	Required       bool               `json:"required"`
	Urgency        HumanReviewUrgency `json:"urgency"`
	ReasonCodes    []string           `json:"reasonCodes"`
	Status         string             `json:"status"`
	ReviewerUserID *uuid.UUID         `json:"reviewerUserId,omitempty"`
	Notes          string             `json:"notes"`
	CompletedAt    *time.Time         `json:"completedAt,omitempty"`
}

type HumanReviewInput struct {
	ReportID               uuid.UUID `json:"reportId"`
	ApprovedForPublication bool      `json:"approvedForPublication"`
	Notes                  string    `json:"notes"`
}

type Interview struct {
	ID                   uuid.UUID         `json:"id"`
	OrganizationID       uuid.UUID         `json:"organizationId"`
	CandidateUserID      *uuid.UUID        `json:"candidateUserId,omitempty"`
	CandidateEmail       string            `json:"candidateEmail"`
	CandidateDisplayName string            `json:"candidateDisplayName"`
	Title                string            `json:"title"`
	PositionTitle        string            `json:"positionTitle"`
	Seniority            string            `json:"seniority"`
	TechnologyTags       []string          `json:"technologyTags"`
	Mode                 InterviewMode     `json:"mode"`
	Language             InterviewLanguage `json:"language"`
	QuestionSource       QuestionSource    `json:"questionSource"`
	RubricVersion        string            `json:"rubricVersion"`
	Status               InterviewStatus   `json:"status"`
	StartsAt             *time.Time        `json:"startsAt,omitempty"`
	ExpiresAt            time.Time         `json:"expiresAt"`
	StartedAt            *time.Time        `json:"startedAt,omitempty"`
	CompletedAt          *time.Time        `json:"completedAt,omitempty"`
	CancelledAt          *time.Time        `json:"cancelledAt,omitempty"`
	Version              int               `json:"version"`
	Questions            []*Question       `json:"questions"`
	Answers              []*Answer         `json:"answers"`
	CreatedAt            time.Time         `json:"createdAt"`
	UpdatedAt            time.Time         `json:"updatedAt"`
}

type InterviewInvitationPayload struct {
	InvitationID uuid.UUID `json:"invitationId"`
	Token        string    `json:"token"`
	ExpiresAt    time.Time `json:"expiresAt"`
}

type Mutation struct {
}

type Organization struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Status    OrganizationStatus `json:"status"`
	CreatedAt time.Time          `json:"createdAt"`
}

type OrganizationMembership struct {
	Organization *Organization    `json:"organization"`
	Status       MembershipStatus `json:"status"`
}

type PublishAdminRubricInput struct {
	Name     string                       `json:"name"`
	Criteria []*AdminRubricCriterionInput `json:"criteria"`
}

type Query struct {
}

type Question struct {
	ID               uuid.UUID    `json:"id"`
	InterviewID      uuid.UUID    `json:"interviewId"`
	Sequence         int          `json:"sequence"`
	Type             QuestionType `json:"type"`
	Prompt           string       `json:"prompt"`
	CompetencyIds    []string     `json:"competencyIds"`
	Difficulty       int          `json:"difficulty"`
	TimeLimitSeconds *int         `json:"timeLimitSeconds,omitempty"`
	CreatedAt        time.Time    `json:"createdAt"`
}

type QuestionDraft struct {
	ID               uuid.UUID           `json:"id"`
	InterviewID      uuid.UUID           `json:"interviewId"`
	RequestedBy      uuid.UUID           `json:"requestedBy"`
	ReviewedBy       *uuid.UUID          `json:"reviewedBy,omitempty"`
	Type             QuestionType        `json:"type"`
	Prompt           string              `json:"prompt"`
	CompetencyIds    []string            `json:"competencyIds"`
	Difficulty       int                 `json:"difficulty"`
	TimeLimitSeconds *int                `json:"timeLimitSeconds,omitempty"`
	Language         InterviewLanguage   `json:"language"`
	Status           QuestionDraftStatus `json:"status"`
	ModelID          string              `json:"modelId"`
	ModelVersion     string              `json:"modelVersion"`
	ReviewNotes      string              `json:"reviewNotes"`
	CreatedAt        time.Time           `json:"createdAt"`
	ReviewedAt       *time.Time          `json:"reviewedAt,omitempty"`
}

type RedeemInterviewInvitationInput struct {
	Token         string `json:"token"`
	PolicyVersion string `json:"policyVersion"`
	Locale        string `json:"locale"`
	Purpose       string `json:"purpose"`
}

type RegisterAdminModelInput struct {
	ModelID       string             `json:"modelId"`
	DisplayName   string             `json:"displayName"`
	ProviderLabel string             `json:"providerLabel"`
	Roles         []AdminLLMRole     `json:"roles"`
	Status        *AdminModelStatus  `json:"status,omitempty"`
	LatencyClass  *AdminLatencyClass `json:"latencyClass,omitempty"`
}

type RejectQuestionDraftInput struct {
	DraftID uuid.UUID `json:"draftId"`
	Notes   string    `json:"notes"`
}

type RequestQuestionDraftInput struct {
	InterviewID      uuid.UUID    `json:"interviewId"`
	Type             QuestionType `json:"type"`
	CompetencyIds    []string     `json:"competencyIds"`
	Difficulty       int          `json:"difficulty"`
	TimeLimitSeconds *int         `json:"timeLimitSeconds,omitempty"`
	TaskBrief        *string      `json:"taskBrief,omitempty"`
}

type SelectOrganizationPayload struct {
	AccessToken  string                  `json:"accessToken"`
	TokenClass   TokenClass              `json:"tokenClass"`
	Organization *Organization           `json:"organization"`
	Membership   *OrganizationMembership `json:"membership"`
}

type SubmitAnswerInput struct {
	InterviewID    uuid.UUID  `json:"interviewId"`
	QuestionID     uuid.UUID  `json:"questionId"`
	Text           *string    `json:"text,omitempty"`
	CodeLanguage   *string    `json:"codeLanguage,omitempty"`
	CodeContent    *string    `json:"codeContent,omitempty"`
	IdempotencyKey uuid.UUID  `json:"idempotencyKey"`
	SupersedesID   *uuid.UUID `json:"supersedesId,omitempty"`
}

type UpdateAdminRoutingInput struct {
	Role            AdminLLMRole `json:"role"`
	PrimaryModelID  string       `json:"primaryModelId"`
	FallbackModelID string       `json:"fallbackModelId"`
	TimeoutSeconds  int          `json:"timeoutSeconds"`
	Enabled         bool         `json:"enabled"`
}

type User struct {
	ID        uuid.UUID  `json:"id"`
	Email     string     `json:"email"`
	FirstName string     `json:"firstName"`
	LastName  string     `json:"lastName"`
	FullName  string     `json:"fullName"`
	Status    UserStatus `json:"status"`
	CreatedAt time.Time  `json:"createdAt"`
}

type AdminLLMRole string

const (
	AdminLLMRoleInterviewer AdminLLMRole = "INTERVIEWER"
	AdminLLMRoleEvaluator   AdminLLMRole = "EVALUATOR"
)

var AllAdminLLMRole = []AdminLLMRole{
	AdminLLMRoleInterviewer,
	AdminLLMRoleEvaluator,
}

func (e AdminLLMRole) IsValid() bool {
	switch e {
	case AdminLLMRoleInterviewer, AdminLLMRoleEvaluator:
		return true
	}
	return false
}

func (e AdminLLMRole) String() string {
	return string(e)
}

func (e *AdminLLMRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AdminLLMRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AdminLLMRole", str)
	}
	return nil
}

func (e AdminLLMRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AdminLLMRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AdminLLMRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AdminLatencyClass string

const (
	AdminLatencyClassFast     AdminLatencyClass = "FAST"
	AdminLatencyClassBalanced AdminLatencyClass = "BALANCED"
	AdminLatencyClassDeep     AdminLatencyClass = "DEEP"
)

var AllAdminLatencyClass = []AdminLatencyClass{
	AdminLatencyClassFast,
	AdminLatencyClassBalanced,
	AdminLatencyClassDeep,
}

func (e AdminLatencyClass) IsValid() bool {
	switch e {
	case AdminLatencyClassFast, AdminLatencyClassBalanced, AdminLatencyClassDeep:
		return true
	}
	return false
}

func (e AdminLatencyClass) String() string {
	return string(e)
}

func (e *AdminLatencyClass) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AdminLatencyClass(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AdminLatencyClass", str)
	}
	return nil
}

func (e AdminLatencyClass) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AdminLatencyClass) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AdminLatencyClass) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AdminModelStatus string

const (
	AdminModelStatusActive   AdminModelStatus = "ACTIVE"
	AdminModelStatusFallback AdminModelStatus = "FALLBACK"
	AdminModelStatusDisabled AdminModelStatus = "DISABLED"
)

var AllAdminModelStatus = []AdminModelStatus{
	AdminModelStatusActive,
	AdminModelStatusFallback,
	AdminModelStatusDisabled,
}

func (e AdminModelStatus) IsValid() bool {
	switch e {
	case AdminModelStatusActive, AdminModelStatusFallback, AdminModelStatusDisabled:
		return true
	}
	return false
}

func (e AdminModelStatus) String() string {
	return string(e)
}

func (e *AdminModelStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AdminModelStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AdminModelStatus", str)
	}
	return nil
}

func (e AdminModelStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AdminModelStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AdminModelStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AdminPromptStatus string

const (
	AdminPromptStatusDraft    AdminPromptStatus = "DRAFT"
	AdminPromptStatusActive   AdminPromptStatus = "ACTIVE"
	AdminPromptStatusArchived AdminPromptStatus = "ARCHIVED"
)

var AllAdminPromptStatus = []AdminPromptStatus{
	AdminPromptStatusDraft,
	AdminPromptStatusActive,
	AdminPromptStatusArchived,
}

func (e AdminPromptStatus) IsValid() bool {
	switch e {
	case AdminPromptStatusDraft, AdminPromptStatusActive, AdminPromptStatusArchived:
		return true
	}
	return false
}

func (e AdminPromptStatus) String() string {
	return string(e)
}

func (e *AdminPromptStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AdminPromptStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AdminPromptStatus", str)
	}
	return nil
}

func (e AdminPromptStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AdminPromptStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AdminPromptStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AnswerStatus string

const (
	AnswerStatusSubmitted  AnswerStatus = "SUBMITTED"
	AnswerStatusSuperseded AnswerStatus = "SUPERSEDED"
)

var AllAnswerStatus = []AnswerStatus{
	AnswerStatusSubmitted,
	AnswerStatusSuperseded,
}

func (e AnswerStatus) IsValid() bool {
	switch e {
	case AnswerStatusSubmitted, AnswerStatusSuperseded:
		return true
	}
	return false
}

func (e AnswerStatus) String() string {
	return string(e)
}

func (e *AnswerStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AnswerStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AnswerStatus", str)
	}
	return nil
}

func (e AnswerStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AnswerStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AnswerStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EvaluationStatus string

const (
	EvaluationStatusDraft                 EvaluationStatus = "DRAFT"
	EvaluationStatusReviewRequired        EvaluationStatus = "REVIEW_REQUIRED"
	EvaluationStatusReadyForHumanDecision EvaluationStatus = "READY_FOR_HUMAN_DECISION"
	EvaluationStatusPublished             EvaluationStatus = "PUBLISHED"
	EvaluationStatusRejected              EvaluationStatus = "REJECTED"
)

var AllEvaluationStatus = []EvaluationStatus{
	EvaluationStatusDraft,
	EvaluationStatusReviewRequired,
	EvaluationStatusReadyForHumanDecision,
	EvaluationStatusPublished,
	EvaluationStatusRejected,
}

func (e EvaluationStatus) IsValid() bool {
	switch e {
	case EvaluationStatusDraft, EvaluationStatusReviewRequired, EvaluationStatusReadyForHumanDecision, EvaluationStatusPublished, EvaluationStatusRejected:
		return true
	}
	return false
}

func (e EvaluationStatus) String() string {
	return string(e)
}

func (e *EvaluationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EvaluationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EvaluationStatus", str)
	}
	return nil
}

func (e EvaluationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EvaluationStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EvaluationStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type HumanReviewUrgency string

const (
	HumanReviewUrgencyNone      HumanReviewUrgency = "NONE"
	HumanReviewUrgencyNormal    HumanReviewUrgency = "NORMAL"
	HumanReviewUrgencyHigh      HumanReviewUrgency = "HIGH"
	HumanReviewUrgencyImmediate HumanReviewUrgency = "IMMEDIATE"
)

var AllHumanReviewUrgency = []HumanReviewUrgency{
	HumanReviewUrgencyNone,
	HumanReviewUrgencyNormal,
	HumanReviewUrgencyHigh,
	HumanReviewUrgencyImmediate,
}

func (e HumanReviewUrgency) IsValid() bool {
	switch e {
	case HumanReviewUrgencyNone, HumanReviewUrgencyNormal, HumanReviewUrgencyHigh, HumanReviewUrgencyImmediate:
		return true
	}
	return false
}

func (e HumanReviewUrgency) String() string {
	return string(e)
}

func (e *HumanReviewUrgency) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HumanReviewUrgency(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HumanReviewUrgency", str)
	}
	return nil
}

func (e HumanReviewUrgency) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *HumanReviewUrgency) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e HumanReviewUrgency) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InterviewLanguage string

const (
	InterviewLanguageTr InterviewLanguage = "TR"
	InterviewLanguageEn InterviewLanguage = "EN"
)

var AllInterviewLanguage = []InterviewLanguage{
	InterviewLanguageTr,
	InterviewLanguageEn,
}

func (e InterviewLanguage) IsValid() bool {
	switch e {
	case InterviewLanguageTr, InterviewLanguageEn:
		return true
	}
	return false
}

func (e InterviewLanguage) String() string {
	return string(e)
}

func (e *InterviewLanguage) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InterviewLanguage(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InterviewLanguage", str)
	}
	return nil
}

func (e InterviewLanguage) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InterviewLanguage) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InterviewLanguage) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InterviewMode string

const (
	InterviewModeAiDisabled      InterviewMode = "AI_DISABLED"
	InterviewModeGUIDEdAi        InterviewMode = "GUIDED_AI"
	InterviewModeAiCollaboration InterviewMode = "AI_COLLABORATION"
)

var AllInterviewMode = []InterviewMode{
	InterviewModeAiDisabled,
	InterviewModeGUIDEdAi,
	InterviewModeAiCollaboration,
}

func (e InterviewMode) IsValid() bool {
	switch e {
	case InterviewModeAiDisabled, InterviewModeGUIDEdAi, InterviewModeAiCollaboration:
		return true
	}
	return false
}

func (e InterviewMode) String() string {
	return string(e)
}

func (e *InterviewMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InterviewMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InterviewMode", str)
	}
	return nil
}

func (e InterviewMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InterviewMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InterviewMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InterviewStatus string

const (
	InterviewStatusDraft      InterviewStatus = "DRAFT"
	InterviewStatusReady      InterviewStatus = "READY"
	InterviewStatusInvited    InterviewStatus = "INVITED"
	InterviewStatusInProgress InterviewStatus = "IN_PROGRESS"
	InterviewStatusCompleted  InterviewStatus = "COMPLETED"
	InterviewStatusCancelled  InterviewStatus = "CANCELLED"
	InterviewStatusExpired    InterviewStatus = "EXPIRED"
)

var AllInterviewStatus = []InterviewStatus{
	InterviewStatusDraft,
	InterviewStatusReady,
	InterviewStatusInvited,
	InterviewStatusInProgress,
	InterviewStatusCompleted,
	InterviewStatusCancelled,
	InterviewStatusExpired,
}

func (e InterviewStatus) IsValid() bool {
	switch e {
	case InterviewStatusDraft, InterviewStatusReady, InterviewStatusInvited, InterviewStatusInProgress, InterviewStatusCompleted, InterviewStatusCancelled, InterviewStatusExpired:
		return true
	}
	return false
}

func (e InterviewStatus) String() string {
	return string(e)
}

func (e *InterviewStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InterviewStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InterviewStatus", str)
	}
	return nil
}

func (e InterviewStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InterviewStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InterviewStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MembershipStatus string

const (
	MembershipStatusActive  MembershipStatus = "ACTIVE"
	MembershipStatusInvited MembershipStatus = "INVITED"
	MembershipStatusRemoved MembershipStatus = "REMOVED"
)

var AllMembershipStatus = []MembershipStatus{
	MembershipStatusActive,
	MembershipStatusInvited,
	MembershipStatusRemoved,
}

func (e MembershipStatus) IsValid() bool {
	switch e {
	case MembershipStatusActive, MembershipStatusInvited, MembershipStatusRemoved:
		return true
	}
	return false
}

func (e MembershipStatus) String() string {
	return string(e)
}

func (e *MembershipStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MembershipStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MembershipStatus", str)
	}
	return nil
}

func (e MembershipStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MembershipStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MembershipStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrganizationStatus string

const (
	OrganizationStatusActive    OrganizationStatus = "ACTIVE"
	OrganizationStatusSuspended OrganizationStatus = "SUSPENDED"
	OrganizationStatusArchived  OrganizationStatus = "ARCHIVED"
)

var AllOrganizationStatus = []OrganizationStatus{
	OrganizationStatusActive,
	OrganizationStatusSuspended,
	OrganizationStatusArchived,
}

func (e OrganizationStatus) IsValid() bool {
	switch e {
	case OrganizationStatusActive, OrganizationStatusSuspended, OrganizationStatusArchived:
		return true
	}
	return false
}

func (e OrganizationStatus) String() string {
	return string(e)
}

func (e *OrganizationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrganizationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrganizationStatus", str)
	}
	return nil
}

func (e OrganizationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrganizationStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrganizationStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type QuestionDraftStatus string

const (
	QuestionDraftStatusPending  QuestionDraftStatus = "PENDING"
	QuestionDraftStatusApproved QuestionDraftStatus = "APPROVED"
	QuestionDraftStatusRejected QuestionDraftStatus = "REJECTED"
)

var AllQuestionDraftStatus = []QuestionDraftStatus{
	QuestionDraftStatusPending,
	QuestionDraftStatusApproved,
	QuestionDraftStatusRejected,
}

func (e QuestionDraftStatus) IsValid() bool {
	switch e {
	case QuestionDraftStatusPending, QuestionDraftStatusApproved, QuestionDraftStatusRejected:
		return true
	}
	return false
}

func (e QuestionDraftStatus) String() string {
	return string(e)
}

func (e *QuestionDraftStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = QuestionDraftStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid QuestionDraftStatus", str)
	}
	return nil
}

func (e QuestionDraftStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *QuestionDraftStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e QuestionDraftStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type QuestionSource string

const (
	QuestionSourceHuman QuestionSource = "HUMAN"
	QuestionSourceAi    QuestionSource = "AI"
)

var AllQuestionSource = []QuestionSource{
	QuestionSourceHuman,
	QuestionSourceAi,
}

func (e QuestionSource) IsValid() bool {
	switch e {
	case QuestionSourceHuman, QuestionSourceAi:
		return true
	}
	return false
}

func (e QuestionSource) String() string {
	return string(e)
}

func (e *QuestionSource) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = QuestionSource(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid QuestionSource", str)
	}
	return nil
}

func (e QuestionSource) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *QuestionSource) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e QuestionSource) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type QuestionType string

const (
	QuestionTypeTechnicalDiscussion QuestionType = "TECHNICAL_DISCUSSION"
	QuestionTypeCoding              QuestionType = "CODING"
	QuestionTypeSystemDesign        QuestionType = "SYSTEM_DESIGN"
	QuestionTypeDebugging           QuestionType = "DEBUGGING"
)

var AllQuestionType = []QuestionType{
	QuestionTypeTechnicalDiscussion,
	QuestionTypeCoding,
	QuestionTypeSystemDesign,
	QuestionTypeDebugging,
}

func (e QuestionType) IsValid() bool {
	switch e {
	case QuestionTypeTechnicalDiscussion, QuestionTypeCoding, QuestionTypeSystemDesign, QuestionTypeDebugging:
		return true
	}
	return false
}

func (e QuestionType) String() string {
	return string(e)
}

func (e *QuestionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = QuestionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid QuestionType", str)
	}
	return nil
}

func (e QuestionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *QuestionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e QuestionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TokenClass string

const (
	TokenClassBootstrap          TokenClass = "BOOTSTRAP"
	TokenClassTenant             TokenClass = "TENANT"
	TokenClassCandidateInterview TokenClass = "CANDIDATE_INTERVIEW"
)

var AllTokenClass = []TokenClass{
	TokenClassBootstrap,
	TokenClassTenant,
	TokenClassCandidateInterview,
}

func (e TokenClass) IsValid() bool {
	switch e {
	case TokenClassBootstrap, TokenClassTenant, TokenClassCandidateInterview:
		return true
	}
	return false
}

func (e TokenClass) String() string {
	return string(e)
}

func (e *TokenClass) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TokenClass(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TokenClass", str)
	}
	return nil
}

func (e TokenClass) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TokenClass) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TokenClass) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "ACTIVE"
	UserStatusInactive  UserStatus = "INACTIVE"
	UserStatusSuspended UserStatus = "SUSPENDED"
)

var AllUserStatus = []UserStatus{
	UserStatusActive,
	UserStatusInactive,
	UserStatusSuspended,
}

func (e UserStatus) IsValid() bool {
	switch e {
	case UserStatusActive, UserStatusInactive, UserStatusSuspended:
		return true
	}
	return false
}

func (e UserStatus) String() string {
	return string(e)
}

func (e *UserStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserStatus", str)
	}
	return nil
}

func (e UserStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
