package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/masterfabric-go/masterfabric/graph/generated"
	"github.com/masterfabric-go/masterfabric/graph/model"
	interviewUsecase "github.com/masterfabric-go/masterfabric/internal/application/interview/usecase"
	aiadminModel "github.com/masterfabric-go/masterfabric/internal/domain/aiadmin/model"
	interviewModel "github.com/masterfabric-go/masterfabric/internal/domain/interview/model"
	infraWS "github.com/masterfabric-go/masterfabric/internal/infrastructure/websocket"
	"github.com/masterfabric-go/masterfabric/internal/shared/authcontext"
	domainErr "github.com/masterfabric-go/masterfabric/internal/shared/errors"
	"github.com/masterfabric-go/masterfabric/internal/shared/pagination"
)

// Questions is the resolver for the questions field.
func (r *interviewResolver) Questions(ctx context.Context, obj *model.Interview) ([]*model.Question, error) {
	if obj == nil {
		return []*model.Question{}, nil
	}
	if len(obj.Questions) > 0 {
		return obj.Questions, nil
	}
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.InterviewUseCase == nil {
		return nil, notConfigured("interview questions")
	}
	values, err := r.InterviewUseCase.ListQuestions(ctx, actor, obj.ID)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Question, 0, len(values))
	for _, value := range values {
		result = append(result, questionGraphQL(value))
	}
	return result, nil
}

// Answers is the resolver for the answers field.
func (r *interviewResolver) Answers(ctx context.Context, obj *model.Interview) ([]*model.Answer, error) {
	if obj == nil {
		return []*model.Answer{}, nil
	}
	if len(obj.Answers) > 0 {
		return obj.Answers, nil
	}
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.InterviewUseCase == nil {
		return nil, notConfigured("interview answers")
	}
	values, err := r.InterviewUseCase.ListAnswers(ctx, actor, obj.ID)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Answer, 0, len(values))
	for _, value := range values {
		result = append(result, answerGraphQL(value))
	}
	return result, nil
}

// SelectOrganization is the resolver for the selectOrganization field.
func (r *mutationResolver) SelectOrganization(ctx context.Context, organizationID uuid.UUID) (*model.SelectOrganizationPayload, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.UseCase == nil {
		return nil, notConfigured("organization context")
	}
	token, selected, err := r.UseCase.SelectOrganization(ctx, actor, organizationID)
	if err != nil {
		return nil, err
	}
	return &model.SelectOrganizationPayload{AccessToken: token, TokenClass: model.TokenClassTenant, Organization: organizationModel(selected.Organization), Membership: membershipModel(selected)}, nil
}

// CreateInterview is the resolver for the createInterview field.
func (r *mutationResolver) CreateInterview(ctx context.Context, input model.CreateInterviewInput) (*model.Interview, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.InterviewUseCase == nil {
		return nil, notConfigured("interview administration")
	}
	value, err := r.InterviewUseCase.Create(ctx, actor, interviewUsecase.CreateInterviewInput{
		Title: input.Title, CandidateEmail: input.CandidateEmail, CandidateDisplayName: input.CandidateDisplayName,
		PositionTitle: input.PositionTitle, Seniority: input.Seniority, TechnologyTags: input.TechnologyTags,
		Mode: interviewModel.Mode(strings.ToLower(string(input.Mode))), RubricVersion: input.RubricVersion,
		Language:       interviewModel.InterviewLanguage(strings.ToLower(stringOrEmpty(input.Language))),
		QuestionSource: interviewModel.QuestionSource(strings.ToLower(stringOrEmptyQuestionSource(input.QuestionSource))),
		StartsAt:       input.StartsAt, ExpiresAt: input.ExpiresAt,
	})
	return interviewGraphQL(value), err
}

// AddQuestion is the resolver for the addQuestion field.
func (r *mutationResolver) AddQuestion(ctx context.Context, input model.CreateQuestionInput) (*model.Question, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.InterviewUseCase == nil {
		return nil, notConfigured("interview administration")
	}
	value, err := r.InterviewUseCase.AddQuestion(ctx, actor, interviewUsecase.CreateQuestionInput{InterviewID: input.InterviewID, Type: interviewModel.QuestionType(strings.ToLower(string(input.Type))), Prompt: input.Prompt, CompetencyIDs: input.CompetencyIds, Difficulty: input.Difficulty, TimeLimitSeconds: input.TimeLimitSeconds})
	return questionGraphQL(value), err
}

// RequestQuestionDraft is the resolver for the requestQuestionDraft field.
func (r *mutationResolver) RequestQuestionDraft(ctx context.Context, input model.RequestQuestionDraftInput) (*model.QuestionDraft, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.QuestionDraftUseCase == nil {
		return nil, notConfigured("AI question drafting")
	}
	brief := ""
	if input.TaskBrief != nil {
		brief = *input.TaskBrief
	}
	value, err := r.QuestionDraftUseCase.RequestDraft(ctx, actor, interviewUsecase.RequestQuestionDraftInput{InterviewID: input.InterviewID, Type: interviewModel.QuestionType(strings.ToLower(string(input.Type))), CompetencyIDs: input.CompetencyIds, Difficulty: input.Difficulty, TimeLimitSeconds: input.TimeLimitSeconds, TaskBrief: brief})
	return questionDraftGraphQL(value), err
}

// ApproveQuestionDraft is the resolver for the approveQuestionDraft field.
func (r *mutationResolver) ApproveQuestionDraft(ctx context.Context, draftID uuid.UUID) (*model.Question, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.QuestionDraftUseCase == nil {
		return nil, notConfigured("AI question drafting")
	}
	value, err := r.QuestionDraftUseCase.ApproveDraft(ctx, actor, draftID)
	return questionGraphQL(value), err
}

// RejectQuestionDraft is the resolver for the rejectQuestionDraft field.
func (r *mutationResolver) RejectQuestionDraft(ctx context.Context, input model.RejectQuestionDraftInput) (*model.QuestionDraft, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.QuestionDraftUseCase == nil {
		return nil, notConfigured("AI question drafting")
	}
	value, err := r.QuestionDraftUseCase.RejectDraft(ctx, actor, input.DraftID, input.Notes)
	return questionDraftGraphQL(value), err
}

// PublishInterview is the resolver for the publishInterview field.
func (r *mutationResolver) PublishInterview(ctx context.Context, interviewID uuid.UUID) (*model.Interview, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.InterviewUseCase == nil {
		return nil, notConfigured("interview administration")
	}
	value, err := r.InterviewUseCase.Publish(ctx, actor, interviewID)
	return interviewGraphQL(value), err
}

// CreateInterviewInvitation is the resolver for the createInterviewInvitation field.
func (r *mutationResolver) CreateInterviewInvitation(ctx context.Context, interviewID uuid.UUID, expiresAt *time.Time) (*model.InterviewInvitationPayload, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.InterviewUseCase == nil {
		return nil, notConfigured("interview administration")
	}
	var expiry time.Time
	if expiresAt != nil {
		expiry = *expiresAt
	}
	value, err := r.InterviewUseCase.CreateInvitation(ctx, actor, interviewID, expiry)
	if err != nil {
		return nil, err
	}
	return &model.InterviewInvitationPayload{InvitationID: value.Invitation.ID, Token: value.Token, ExpiresAt: value.Invitation.ExpiresAt}, nil
}

// RedeemInterviewInvitation is the resolver for the redeemInterviewInvitation field.
func (r *mutationResolver) RedeemInterviewInvitation(ctx context.Context, input model.RedeemInterviewInvitationInput) (*model.CandidateInterviewAccess, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.InterviewUseCase == nil {
		return nil, notConfigured("candidate interview access")
	}
	value, err := r.InterviewUseCase.RedeemInvitation(ctx, actor, interviewUsecase.RedeemInvitationInput{Token: input.Token, PolicyVersion: input.PolicyVersion, Locale: input.Locale, Purpose: input.Purpose})
	if err != nil {
		return nil, err
	}
	return &model.CandidateInterviewAccess{AccessToken: value.AccessToken, TokenClass: model.TokenClassCandidateInterview, Interview: interviewGraphQL(value.Interview)}, nil
}

// StartInterview is the resolver for the startInterview field.
func (r *mutationResolver) StartInterview(ctx context.Context, interviewID uuid.UUID) (*model.Interview, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.InterviewUseCase == nil {
		return nil, notConfigured("candidate interview")
	}
	value, err := r.InterviewUseCase.Start(ctx, actor, interviewID)
	return interviewGraphQL(value), err
}

// SubmitAnswer is the resolver for the submitAnswer field.
func (r *mutationResolver) SubmitAnswer(ctx context.Context, input model.SubmitAnswerInput) (*model.Answer, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.InterviewUseCase == nil {
		return nil, notConfigured("candidate interview")
	}
	value, err := r.InterviewUseCase.SubmitAnswer(ctx, actor, interviewUsecase.SubmitAnswerInput{InterviewID: input.InterviewID, QuestionID: input.QuestionID, Text: input.Text, CodeLanguage: input.CodeLanguage, CodeContent: input.CodeContent, IdempotencyKey: input.IdempotencyKey, SupersedesID: input.SupersedesID})
	return answerGraphQL(value), err
}

// CompleteInterview is the resolver for the completeInterview field.
func (r *mutationResolver) CompleteInterview(ctx context.Context, interviewID uuid.UUID) (*model.Interview, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.InterviewUseCase == nil {
		return nil, notConfigured("candidate interview")
	}
	value, err := r.InterviewUseCase.Complete(ctx, actor, interviewID)
	return interviewGraphQL(value), err
}

// CancelInterview is the resolver for the cancelInterview field.
func (r *mutationResolver) CancelInterview(ctx context.Context, interviewID uuid.UUID) (*model.Interview, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.InterviewUseCase == nil {
		return nil, notConfigured("interview administration")
	}
	value, err := r.InterviewUseCase.Cancel(ctx, actor, interviewID)
	return interviewGraphQL(value), err
}

// RequestEvaluation is the resolver for the requestEvaluation field.
func (r *mutationResolver) RequestEvaluation(ctx context.Context, interviewID uuid.UUID) (*model.EvaluationReport, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.EvaluationUseCase == nil {
		return nil, notConfigured("evaluation")
	}
	value, err := r.EvaluationUseCase.RequestEvaluation(ctx, actor, interviewID)
	return evaluationReportGraphQL(value), err
}

// RecordHumanReview is the resolver for the recordHumanReview field.
func (r *mutationResolver) RecordHumanReview(ctx context.Context, input model.HumanReviewInput) (*model.EvaluationReport, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.EvaluationUseCase == nil {
		return nil, notConfigured("evaluation")
	}
	value, err := r.EvaluationUseCase.RecordHumanReview(ctx, actor, input.ReportID, input.ApprovedForPublication, input.Notes)
	return evaluationReportGraphQL(value), err
}

// RegisterAdminModel is the resolver for the registerAdminModel field.
func (r *mutationResolver) RegisterAdminModel(ctx context.Context, input model.RegisterAdminModelInput) (*model.AdminModel, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.AIAdminUseCase == nil {
		return nil, notConfigured("AI administration")
	}
	status := aiadminModel.ModelActive
	if input.Status != nil {
		status = aiadminModel.ModelStatus(strings.ToLower(string(*input.Status)))
	}
	latency := aiadminModel.LatencyBalanced
	if input.LatencyClass != nil {
		latency = aiadminModel.LatencyClass(strings.ToLower(string(*input.LatencyClass)))
	}
	roles := make([]aiadminModel.Role, 0, len(input.Roles))
	for _, role := range input.Roles {
		roles = append(roles, aiadminModel.Role(strings.ToLower(string(role))))
	}
	value, err := r.AIAdminUseCase.RegisterModel(ctx, actor, aiadminModel.RegisterModelInput{ModelID: input.ModelID, DisplayName: input.DisplayName, ProviderLabel: input.ProviderLabel, Roles: roles, Status: status, LatencyClass: latency})
	return adminModelGraphQL(value), err
}

// CreateAdminPromptVersion is the resolver for the createAdminPromptVersion field.
func (r *mutationResolver) CreateAdminPromptVersion(ctx context.Context, input model.CreateAdminPromptVersionInput) (*model.AdminPromptConfiguration, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.AIAdminUseCase == nil {
		return nil, notConfigured("AI administration")
	}
	value, err := r.AIAdminUseCase.CreatePromptVersion(ctx, actor, aiadminModel.CreatePromptInput{Role: aiadminModel.Role(strings.ToLower(string(input.Role))), Name: input.Name, Prompt: input.PromptTemplate})
	return adminPromptGraphQL(value), err
}

// UpdateAdminRouting is the resolver for the updateAdminRouting field.
func (r *mutationResolver) UpdateAdminRouting(ctx context.Context, input model.UpdateAdminRoutingInput) (*model.AdminRoutingRule, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.AIAdminUseCase == nil {
		return nil, notConfigured("AI administration")
	}
	value, err := r.AIAdminUseCase.UpdateRouting(ctx, actor, aiadminModel.UpdateRoutingInput{Role: aiadminModel.Role(strings.ToLower(string(input.Role))), PrimaryModelID: input.PrimaryModelID, FallbackModelID: input.FallbackModelID, TimeoutSeconds: input.TimeoutSeconds, Enabled: input.Enabled})
	return adminRoutingGraphQL(value), err
}

// PublishAdminRubric is the resolver for the publishAdminRubric field.
func (r *mutationResolver) PublishAdminRubric(ctx context.Context, input model.PublishAdminRubricInput) (*model.AdminEvaluationRubric, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.AIAdminUseCase == nil {
		return nil, notConfigured("AI administration")
	}
	criteria := make([]aiadminModel.RubricCriterion, 0, len(input.Criteria))
	for _, criterion := range input.Criteria {
		criteria = append(criteria, aiadminModel.RubricCriterion{Name: criterion.Name, Weight: criterion.Weight})
	}
	value, err := r.AIAdminUseCase.PublishRubric(ctx, actor, aiadminModel.PublishRubricInput{Name: input.Name, Criteria: criteria})
	return adminRubricGraphQL(value), err
}

// ApproveAdminConfiguration is the resolver for the approveAdminConfiguration field.
func (r *mutationResolver) ApproveAdminConfiguration(ctx context.Context, resource string, resourceKey string, version int) (*model.AdminConfigurationVersion, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.AIAdminUseCase == nil {
		return nil, notConfigured("AI administration")
	}
	value, err := r.AIAdminUseCase.ApproveConfiguration(ctx, actor, resource, resourceKey, version)
	return adminVersionGraphQL(value), err
}

// RollbackAdminConfiguration is the resolver for the rollbackAdminConfiguration field.
func (r *mutationResolver) RollbackAdminConfiguration(ctx context.Context, resource string, resourceKey string, version int) (*model.AdminConfigurationVersion, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.AIAdminUseCase == nil {
		return nil, notConfigured("AI administration")
	}
	value, err := r.AIAdminUseCase.RollbackConfiguration(ctx, actor, resource, resourceKey, version)
	return adminVersionGraphQL(value), err
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.UseCase == nil {
		return nil, notConfigured("identity")
	}
	value, err := r.UseCase.GetMe(ctx, actor)
	if err != nil {
		return nil, err
	}
	return &model.User{ID: value.ID, Email: value.Email, FirstName: value.FirstName, LastName: value.LastName, FullName: value.FirstName + " " + value.LastName, Status: model.UserStatus(strings.ToUpper(value.Status)), CreatedAt: value.CreatedAt}, nil
}

// Organizations is the resolver for the organizations field.
func (r *queryResolver) Organizations(ctx context.Context) ([]*model.OrganizationMembership, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.UseCase == nil {
		return nil, notConfigured("organization context")
	}
	values, err := r.UseCase.ListOrganizations(ctx, actor)
	if err != nil {
		return nil, err
	}
	result := make([]*model.OrganizationMembership, 0, len(values))
	for _, value := range values {
		result = append(result, membershipModel(value))
	}
	return result, nil
}

// Interviews is the resolver for the interviews field.
func (r *queryResolver) Interviews(ctx context.Context, statuses []model.InterviewStatus, limit *int) ([]*model.Interview, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.InterviewUseCase == nil {
		return nil, notConfigured("interview administration")
	}
	domainStatuses := make([]interviewModel.Status, 0, len(statuses))
	for _, status := range statuses {
		domainStatuses = append(domainStatuses, interviewModel.Status(strings.ToLower(string(status))))
	}
	pageSize := 50
	if limit != nil {
		pageSize = *limit
	}
	values, err := r.InterviewUseCase.List(ctx, actor, domainStatuses, pageSize)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Interview, 0, len(values))
	for _, value := range values {
		result = append(result, interviewGraphQL(value))
	}
	return result, nil
}

// InterviewConnection is the keyset-paginated form of interviews. It keeps
// the existing list field backward-compatible while new clients can avoid
// offset drift and unbounded page requests.
func (r *queryResolver) InterviewConnection(ctx context.Context, statuses []model.InterviewStatus, first *int, after *string) (*model.InterviewConnection, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.InterviewUseCase == nil {
		return nil, notConfigured("interview administration")
	}
	pageSize := 20
	if first != nil {
		pageSize = *first
	}
	var cursor *pagination.Cursor
	if after != nil && strings.TrimSpace(*after) != "" {
		decoded, decodeErr := pagination.DecodeCursor(*after)
		if decodeErr != nil {
			return nil, domainErr.New(domainErr.ErrValidation, "after cursor is invalid", decodeErr)
		}
		cursor = &decoded
	}
	domainStatuses := make([]interviewModel.Status, 0, len(statuses))
	for _, status := range statuses {
		domainStatuses = append(domainStatuses, interviewModel.Status(strings.ToLower(string(status))))
	}
	page, err := r.InterviewUseCase.ListPage(ctx, actor, domainStatuses, cursor, pageSize)
	if err != nil {
		return nil, err
	}
	edges := make([]*model.InterviewEdge, 0, len(page.Items))
	for _, value := range page.Items {
		edgeCursor, cursorErr := pagination.EncodeCursor(value.CreatedAt, value.ID)
		if cursorErr != nil {
			return nil, domainErr.New(domainErr.ErrInternal, "failed to encode interview cursor", cursorErr)
		}
		edges = append(edges, &model.InterviewEdge{Cursor: edgeCursor, Node: interviewGraphQL(value)})
	}
	var endCursor *string
	if page.EndCursor != "" {
		endCursor = &page.EndCursor
	}
	return &model.InterviewConnection{Edges: edges, PageInfo: &model.PageInfo{HasNextPage: page.HasNextPage, EndCursor: endCursor}}, nil
}

// Interview is the resolver for the interview field.
func (r *queryResolver) Interview(ctx context.Context, id uuid.UUID) (*model.Interview, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.InterviewUseCase == nil {
		return nil, notConfigured("interview")
	}
	value, err := r.InterviewUseCase.Get(ctx, actor, id)
	return interviewGraphQL(value), err
}

// Question is the resolver for the question field.
func (r *queryResolver) Question(ctx context.Context, id uuid.UUID) (*model.Question, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.InterviewUseCase == nil {
		return nil, notConfigured("question")
	}
	value, err := r.InterviewUseCase.GetQuestion(ctx, actor, id)
	return questionGraphQL(value), err
}

// Answer is the resolver for the answer field.
func (r *queryResolver) Answer(ctx context.Context, id uuid.UUID) (*model.Answer, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.InterviewUseCase == nil {
		return nil, notConfigured("answer")
	}
	value, err := r.InterviewUseCase.GetAnswer(ctx, actor, id)
	return answerGraphQL(value), err
}

// QuestionDraft is the resolver for the questionDraft field.
func (r *queryResolver) QuestionDraft(ctx context.Context, id uuid.UUID) (*model.QuestionDraft, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.QuestionDraftUseCase == nil {
		return nil, notConfigured("AI question drafting")
	}
	value, err := r.QuestionDraftUseCase.GetDraft(ctx, actor, id)
	return questionDraftGraphQL(value), err
}

// EvaluationReport is the resolver for the evaluationReport field.
func (r *queryResolver) EvaluationReport(ctx context.Context, interviewID uuid.UUID) (*model.EvaluationReport, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.EvaluationUseCase == nil {
		return nil, notConfigured("evaluation")
	}
	value, err := r.EvaluationUseCase.GetReport(ctx, actor, interviewID)
	return evaluationReportGraphQL(value), err
}

// AdminWorkspace is the resolver for the adminWorkspace field.
func (r *queryResolver) AdminWorkspace(ctx context.Context) (*model.AdminWorkspace, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.AIAdminUseCase == nil {
		return nil, notConfigured("AI administration")
	}
	value, err := r.AIAdminUseCase.Workspace(ctx, actor)
	return adminWorkspaceGraphQL(value), err
}

// AdminAuditEvents is the independently bounded, tenant-scoped audit
// connection. It requires the same admin MFA/read policy as the workspace.
func (r *queryResolver) AdminAuditEvents(ctx context.Context, first *int, after *string) (*model.AdminAuditConnection, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if r.AIAdminUseCase == nil {
		return nil, notConfigured("audit administration")
	}
	pageSize := 50
	if first != nil {
		pageSize = *first
	}
	var cursor *pagination.Cursor
	if after != nil && strings.TrimSpace(*after) != "" {
		decoded, decodeErr := pagination.DecodeCursor(*after)
		if decodeErr != nil {
			return nil, domainErr.New(domainErr.ErrValidation, "after cursor is invalid", decodeErr)
		}
		cursor = &decoded
	}
	page, err := r.AIAdminUseCase.AuditPage(ctx, actor, cursor, pageSize)
	if err != nil {
		return nil, err
	}
	edges := make([]*model.AdminAuditEventEdge, 0, len(page.Events))
	for _, value := range page.Events {
		edgeCursor, cursorErr := pagination.EncodeCursor(value.OccurredAt, value.ID)
		if cursorErr != nil {
			return nil, domainErr.New(domainErr.ErrInternal, "failed to encode audit cursor", cursorErr)
		}
		edges = append(edges, &model.AdminAuditEventEdge{Cursor: edgeCursor, Node: adminAuditEventGraphQL(value)})
	}
	var endCursor *string
	if page.EndCursor != "" {
		endCursor = &page.EndCursor
	}
	return &model.AdminAuditConnection{Edges: edges, PageInfo: &model.PageInfo{HasNextPage: page.HasNextPage, EndCursor: endCursor}}, nil
}

// InterviewUpdated is the resolver for the interviewUpdated field.
func (r *subscriptionResolver) InterviewUpdated(ctx context.Context, interviewID uuid.UUID, after *string) (<-chan *model.InterviewUpdated, error) {
	actor, err := requireActor(ctx)
	if err != nil {
		return nil, err
	}
	if interviewID == uuid.Nil || actor.OrganizationID == uuid.Nil {
		return nil, domainErr.New(domainErr.ErrValidation, "interview subscription scope is required", nil)
	}
	switch actor.TokenClass {
	case authcontext.TokenClassCandidateInterview:
		if actor.InterviewID != interviewID || !hasPermission(actor.Permissions, "interview:participate") {
			return nil, domainErr.New(domainErr.ErrForbidden, "interview subscription access denied", nil)
		}
	case authcontext.TokenClassTenant:
		if !hasPermission(actor.Permissions, "interview:read") {
			return nil, domainErr.New(domainErr.ErrForbidden, "interview subscription access denied", nil)
		}
	default:
		return nil, domainErr.New(domainErr.ErrForbidden, "interview subscription access denied", nil)
	}
	if r.SubscriptionBroker == nil {
		return nil, notConfigured("interview subscriptions")
	}
	afterCursor := ""
	if after != nil {
		afterCursor = *after
	}
	updates, err := r.SubscriptionBroker.Subscribe(ctx, actor.OrganizationID, interviewID, afterCursor)
	if err != nil {
		switch {
		case errors.Is(err, infraWS.ErrReplayCursorInvalid):
			return nil, domainErr.New(domainErr.ErrValidation, "interview subscription cursor is invalid", err)
		case errors.Is(err, infraWS.ErrReplayCursorExpired):
			return nil, domainErr.New(domainErr.ErrConflict, "interview subscription cursor has expired; refetch interview state", err)
		case errors.Is(err, infraWS.ErrReplayGap):
			return nil, domainErr.New(domainErr.ErrConflict, "interview subscription cursor has a replay gap; refetch interview state", err)
		case errors.Is(err, infraWS.ErrReplayLimit):
			return nil, domainErr.New(domainErr.ErrConflict, "interview subscription replay is too large; refetch interview state", err)
		default:
			return nil, domainErr.New(domainErr.ErrInternal, "interview subscription unavailable", err)
		}
	}
	stream := make(chan *model.InterviewUpdated, 16)
	go func() {
		defer close(stream)
		for update := range updates {
			stream <- &model.InterviewUpdated{InterviewID: update.InterviewID, Cursor: update.Cursor, EventType: update.EventType, Status: update.Status, Version: update.Version, OccurredAt: update.OccurredAt}
		}
	}()
	return stream, nil
}

// Interview returns generated.InterviewResolver implementation.
func (r *Resolver) Interview() generated.InterviewResolver { return &interviewResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type interviewResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
