import { Bot, CheckCircle2, Clock3, Code2, ShieldCheck, Wifi, WifiOff } from "lucide-react";
import type { Interview, Question } from "@/core/domain/interview";
import { Badge } from "@/components/ui/badge";
import styles from "@/features/interviews/view/chat.module.css";

function formatTime(seconds: number): string { const safe = Math.max(0, seconds); const minutes = Math.floor(safe / 60); const remainder = safe % 60; return String(minutes).padStart(2, "0") + ":" + String(remainder).padStart(2, "0"); }

export function SessionPanel({ interview, question, candidateResponse, remainingSeconds, isOnline, answeredCount, totalQuestions, isExpired }: { interview: Interview; question: Question | null; candidateResponse: string; remainingSeconds: number; isOnline: boolean; answeredCount: number; totalQuestions: number; isExpired: boolean }) {
  const progress = totalQuestions ? Math.round((answeredCount / totalQuestions) * 100) : 0;
  return <aside className="session-panel" aria-label="Interview session details">
    <section className={styles.conversation}><div className={styles.header}><div className={styles.title}><Bot aria-hidden="true" /><p className="panel-label">Conversation</p></div><Badge>Live context</Badge></div><div className={styles.messages} role="log" aria-live="polite" aria-label="Interview conversation">{question ? <article className={styles.message}><header><strong>Interviewer</strong><span>Current question</span></header><p>{question.prompt}</p></article> : <p className={styles.empty}>There is no active question.</p>}{candidateResponse.trim() ? <article className={styles.message + " " + styles.candidate}><header><strong>You</strong><span>Draft answer</span></header><p>{candidateResponse}</p></article> : question && <p className={styles.empty}>Your written answer will appear here as you type.</p>}</div><p className={styles.note}>This conversation mirrors the active question and your current draft.</p></section>
    <section><p className="panel-label">Time remaining</p><div className="session-timer"><Clock3 aria-hidden="true" /><strong aria-live="polite">{formatTime(remainingSeconds)}</strong></div><span className="session-note">{isExpired ? "Session expired; answers are read-only." : "Session ends automatically at 00:00"}</span></section>
    <section><p className="panel-label">Session status</p><div className="status-line">{isOnline ? <Wifi aria-hidden="true" /> : <WifiOff aria-hidden="true" />}<div><strong>{isOnline ? "Connected" : "Offline"}</strong><span>{isOnline ? "Explicit saves sync to the server" : "Drafts remain available locally"}</span></div></div><div className="status-line"><CheckCircle2 aria-hidden="true" /><div><strong>Question {question?.sequence ?? 0} of {totalQuestions}</strong><span>{progress}% complete</span></div></div></section>
    <section><p className="panel-label">Technical context</p>{question ? <div className="context-list"><span><Code2 /> Interview <strong>{interview.title}</strong></span><span><Code2 /> Language <strong>TypeScript</strong></span><span><ShieldCheck /> Difficulty <strong>{question.difficulty}</strong></span><span><Clock3 /> Suggested <strong>{question.expectedMinutes} min</strong></span></div> : <p className="muted">No question context is available.</p>}</section>
    <section className="ai-session"><div><Bot aria-hidden="true" /><p className="panel-label">AI interviewer</p></div><Badge>Structured mode</Badge><p>Follow-ups are limited to job-relevant technical evidence. No facial, emotion, or personality analysis is used.</p></section>
  </aside>;
}
